stages:
  - build
  - test
  - docker

variables:
  BUILD_CONFIGURATION: "Release"
  IMAGE_NAME: "guessitapi"

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet restore
    - dotnet build -c $BUILD_CONFIGURATION
  artifacts:
    paths:
      - bin/
      - obj/

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet test --no-build --verbosity normal

docker:
  stage: docker
  image: docker:24.0.2
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  script:
    # логинимся в Docker, если нужно
    # - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker stop guessitapi || true
    - docker rm guessitapi || true
    - docker run -d \
        --name guessitapi \
        --network proxy \
        -e VIRTUAL_HOST=guessitapi.antishelkon.ru \
        -e LETSENCRYPT_HOST=guessitapi.antishelkon.ru \
        $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
